<a href="https://colab.research.google.com/github/muhamadr03/Praktikum-ML/blob/main/Praktikum%20Mandiri%2010/PraktikumMandiri10.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd

from sklearn.metrics import (
    confusion_matrix, accuracy_score,
    precision_score, recall_score,
    classification_report
)
from sklearn.neighbors import KNeighborsClassifier
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import OneHotEncoder, StandardScaler
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline


In [ ]:
# ===== LATIHAN 1 =====

# Data training (temperatur, kecepatan angin)
X1 = np.array([
    [10, 0],
    [25, 0],
    [15, 5],
    [20, 3],
    [18, 7],
    [20,10],
    [22, 5],
    [24, 6]
])
y1 = np.array(["Dingin","Panas","Dingin","Panas",
               "Dingin","Dingin","Panas","Panas"])



In [ ]:
# Model KNN k=3
knn1 = KNeighborsClassifier(n_neighbors=3)
knn1.fit(X1, y1)

KNeighborsClassifier(n_neighbors=3)

In [ ]:
# Prediksi persepsi Marry (16°C, 3 km/jam)
pred1 = knn1.predict([[16, 3]])
print("Persepsi Marry untuk (T=16, angin=3):", pred1[0])

Persepsi Marry untuk (T=16, angin=3): Dingin


In [ ]:
# Cari k terbaik (contoh sederhana)
X1_train, X1_test, y1_train, y1_test = train_test_split(
    X1, y1, test_size=0.25, random_state=42
)

print("\nUji akurasi untuk berbagai k (Latihan 1):")
best_k1, best_acc1 = None, 0
for k in range(1, 7):
    knn_k = KNeighborsClassifier(n_neighbors=k)
    knn_k.fit(X1_train, y1_train)
    y1_pred_k = knn_k.predict(X1_test)
    acc_k = accuracy_score(y1_test, y1_pred_k)
    print(f"k={k}, accuracy={acc_k:.2f}")
    if acc_k > best_acc1:
        best_acc1, best_k1 = acc_k, k

print(f"\nNilai k terbaik (Latihan 1): k={best_k1}, accuracy={best_acc1:.2f}")


Uji akurasi untuk berbagai k (Latihan 1):
k=1, accuracy=1.00
k=2, accuracy=1.00
k=3, accuracy=0.50
k=4, accuracy=0.50
k=5, accuracy=0.50
k=6, accuracy=0.50

Nilai k terbaik (Latihan 1): k=1, accuracy=1.00


In [ ]:
# ===== LATIHAN 2 =====

data2 = {
    "NIM"       : ["TI001", "TI002", "TI003", "TI004", "TI005", "TI006",
                   "TI007", "TI008", "TI009", "TI010"],
    "actual"    : ["Lulus", "Lulus", "Lulus", "Lulus", "Lulus", "Tidak Lulus",
                   "Tidak Lulus", "Tidak Lulus", "Tidak Lulus", "Tidak Lulus"],
    "prediksi"  : ["Lulus", "Lulus", "Lulus", "Tidak Lulus", "Tidak Lulus",
                   "Lulus", "Tidak Lulus", "Tidak Lulus", "Tidak Lulus", "Tidak Lulus"]
}
df2 = pd.DataFrame(data2)

In [ ]:
y2_true = df2["actual"]
y2_pred = df2["prediksi"]
labels2 = ["Lulus", "Tidak Lulus"]

In [ ]:
cm2 = confusion_matrix(y2_true, y2_pred, labels=labels2)
cm2_df = pd.DataFrame(
    cm2,
    index=[f"Actual_{l}" for l in labels2],
    columns=[f"Pred_{l}" for l in labels2]
)
print("Confusion Matrix (Latihan 2):")
print(cm2_df)

Confusion Matrix (Latihan 2):
                    Pred_Lulus  Pred_Tidak Lulus
Actual_Lulus                 3                 2
Actual_Tidak Lulus           1                 4


In [ ]:
acc2  = accuracy_score(y2_true, y2_pred)
prec2 = precision_score(y2_true, y2_pred, pos_label="Lulus")
rec2  = recall_score(y2_true, y2_pred, pos_label="Lulus")

print("\nAccuracy :", acc2)
print("Precision:", prec2)
print("Recall   :", rec2)


Accuracy : 0.7
Precision: 0.75
Recall   : 0.6


In [ ]:
# ===== LATIHAN 3 – dataset manual =====

data3 = {
    "Temperature"           : [14.0, 39.0, 30.0, 38.0, 27.0, 32.0, -2.0, 3.0, 3.0, 28.0],
    "Humidity"              : [73, 96, 64, 83, 74, 55, 97, 85, 83, 74],
    "Wind Speed"            : [9.5, 8.5, 7.0, 1.5, 17.0, 3.5, 8.0, 6.0, 6.0, 8.5],
    "Precipitation (%)"     : [82.0, 71.0, 16.0, 82.0, 66.0, 26.0, 86.0, 96.0, 66.0,107.0],
    "Cloud Cover"           : ["partly cloudy","partly cloudy","clear","clear","overcast",
                               "overcast","overcast","partly cloudy","overcast","clear"],
    "Atmospheric Pressure"  : [1010.82, 1011.43, 1018.72, 1026.25, 990.67, 1010.03, 990.87,
                               984.46, 999.44, 1012.13],
    "UV Index"              : [2, 7, 5, 7, 1, 2, 1, 1, 0, 8],
    "Season"                : ["Winter", "Spring", "Spring", "Spring", "Winter", "Summer",
                               "Winter", "Winter", "Winter", "Winter"],
    "Visibility (km)"       : [3.5, 10.0, 5.5, 1.0, 2.5, 5.0, 4.0, 3.5, 1.0, 7.5],
    "Location"              : ["inland", "inland", "mountain", "coastal", "mountain", "inland",
                               "inland", "inland", "mountain", "coastal"],
    "Weather Type"          : ["Rainy", "Cloudy", "Sunny", "Sunny", "Rainy", "Cloudy", "Snowy", "Snowy", "Snowy", "Sunny"]
}

df3 = pd.DataFrame(data3)
df3.head()


Temperature  Humidity  Wind Speed  Precipitation (%)    Cloud Cover  \
0         14.0        73         9.5               82.0  partly cloudy   
1         39.0        96         8.5               71.0  partly cloudy   
2         30.0        64         7.0               16.0          clear   
3         38.0        83         1.5               82.0          clear   
4         27.0        74        17.0               66.0       overcast   

   Atmospheric Pressure  UV Index  Season  Visibility (km)  Location  \
0               1010.82         2  Winter              3.5    inland   
1               1011.43         7  Spring             10.0    inland   
2               1018.72         5  Spring              5.5  mountain   
3               1026.25         7  Spring              1.0   coastal   
4                990.67         1  Winter              2.5  mountain   

  Weather Type  
0        Rainy  
1       Cloudy  
2        Sunny  
3        Sunny  
4        Rainy

In [ ]:
# ===== LATIHAN 3 – model KNN =====

X3 = df3.drop(columns=["Weather Type"])
y3 = df3["Weather Type"]

num_cols3 = X3.select_dtypes(include=["int64","float64"]).columns.tolist()
cat_cols3 = X3.select_dtypes(include=["object"]).columns.tolist()

preprocess3 = ColumnTransformer(
    transformers=[
        ("num", StandardScaler(), num_cols3),
        ("cat", OneHotEncoder(handle_unknown="ignore"), cat_cols3)
    ]
)

knn3 = KNeighborsClassifier(n_neighbors=3)
model3 = Pipeline(steps=[
    ("preprocess", preprocess3),
    ("knn", knn3)
])



In [ ]:
X3_train, X3_test, y3_train, y3_test = train_test_split(
    X3, y3, test_size=0.4, random_state=42, stratify=y3
)

model3.fit(X3_train, y3_train)
y3_pred = model3.predict(X3_test)

print("Accuracy (Latihan 3):", accuracy_score(y3_test, y3_pred))
print("\nConfusion Matrix:")
print(confusion_matrix(y3_test, y3_pred))
print("\nClassification Report:")
print(classification_report(y3_test, y3_pred))

Accuracy (Latihan 3): 0.5

Confusion Matrix:
[[1 0 0 0]
 [0 0 1 0]
 [0 0 1 0]
 [1 0 0 0]]

Classification Report:
              precision    recall  f1-score   support

      Cloudy       0.50      1.00      0.67         1
       Rainy       0.00      0.00      0.00         1
       Snowy       0.50      1.00      0.67         1
       Sunny       0.00      0.00      0.00         1

    accuracy                           0.50         4
   macro avg       0.25      0.50      0.33         4
weighted avg       0.25      0.50      0.33         4



/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
